# docker exec -it db2 bash -c 'su - db2inst1'
include:
  - path: ../hadoop/docker-compose.yml

services:
  clickhouse:
    container_name: clickhouse
    image: docker.io/bitnami/clickhouse:23
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
      - 9000:9000
    volumes:
      - clickhouse_data:/bitnami/clickhouse
    networks:
      - docker-net

  # pg_db:
  #   container_name: postgres
  #   image: postgres:13
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./ny_taxi_pgdata:/var/lib/postgresql/data:rw
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - docker-net 


  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   ports:
  #     - 8080:80
  #   networks:
  #     - docker-net 

  # hive:
  #   container_name: hive
  #   image: apache/hive:4.0.0-beta-1
  #   ports:
  #     - 10000:10000
  #     - 10002:10002
  #   environment:
  #     - SERVICE_NAME=hiveserver2
  #   networks:
  #     - docker-net
volumes:
  clickhouse_data:
    driver: local
